// Extracted from https://github.com/kevinroberts/city-timezones
// `jq 'sort_by(.pop) | reverse | [limit(128; .[])] | map({city, city_ascii, country, iso2, timezone})'`

export default [
  {
    city: 'Tokyo',
    city_ascii: 'Tokyo',
    country: 'Japan',
    iso2: 'JP',
    timezone: 'Asia/Tokyo',
  },
  {
    city: 'Mumbai',
    city_ascii: 'Mumbai',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Mexico City',
    city_ascii: 'Mexico City',
    country: 'Mexico',
    iso2: 'MX',
    timezone: 'America/Mexico_City',
  },
  {
    city: 'Shanghai',
    city_ascii: 'Shanghai',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Sao Paulo',
    city_ascii: 'Sao Paulo',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Sao_Paulo',
  },
  {
    city: 'New York',
    city_ascii: 'New York',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/New_York',
  },
  {
    city: 'Karachi',
    city_ascii: 'Karachi',
    country: 'Pakistan',
    iso2: 'PK',
    timezone: 'Asia/Karachi',
  },
  {
    city: 'Buenos Aires',
    city_ascii: 'Buenos Aires',
    country: 'Argentina',
    iso2: 'AR',
    timezone: 'America/Argentina/Buenos_Aires',
  },
  {
    city: 'Delhi',
    city_ascii: 'Delhi',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Moscow',
    city_ascii: 'Moscow',
    country: 'Russia',
    iso2: 'RU',
    timezone: 'Europe/Moscow',
  },
  {
    city: 'Istanbul',
    city_ascii: 'Istanbul',
    country: 'Turkey',
    iso2: 'TR',
    timezone: 'Europe/Istanbul',
  },
  {
    city: 'Dhaka',
    city_ascii: 'Dhaka',
    country: 'Bangladesh',
    iso2: 'BD',
    timezone: 'Asia/Dhaka',
  },
  {
    city: 'Cairo',
    city_ascii: 'Cairo',
    country: 'Egypt',
    iso2: 'EG',
    timezone: 'Africa/Cairo',
  },
  {
    city: 'Seoul',
    city_ascii: 'Seoul',
    country: 'South Korea',
    iso2: 'KR',
    timezone: 'Asia/Seoul',
  },
  {
    city: 'Kolkata',
    city_ascii: 'Kolkata',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Beijing',
    city_ascii: 'Beijing',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Jakarta',
    city_ascii: 'Jakarta',
    country: 'Indonesia',
    iso2: 'ID',
    timezone: 'Asia/Jakarta',
  },
  {
    city: 'Los Angeles',
    city_ascii: 'Los Angeles',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/Los_Angeles',
  },
  {
    city: 'London',
    city_ascii: 'London',
    country: 'United Kingdom',
    iso2: 'GB',
    timezone: 'Europe/London',
  },
  {
    city: 'Tehran',
    city_ascii: 'Tehran',
    country: 'Iran',
    iso2: 'IR',
    timezone: 'Asia/Tehran',
  },
  {
    city: 'Lima',
    city_ascii: 'Lima',
    country: 'Peru',
    iso2: 'PE',
    timezone: 'America/Lima',
  },
  {
    city: 'Manila',
    city_ascii: 'Manila',
    country: 'Philippines',
    iso2: 'PH',
    timezone: 'Asia/Manila',
  },
  {
    city: 'Bogota',
    city_ascii: 'Bogota',
    country: 'Colombia',
    iso2: 'CO',
    timezone: 'America/Bogota',
  },
  {
    city: 'Osaka',
    city_ascii: 'Osaka',
    country: 'Japan',
    iso2: 'JP',
    timezone: 'Asia/Tokyo',
  },
  {
    city: 'Rio de Janeiro',
    city_ascii: 'Rio de Janeiro',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Sao_Paulo',
  },
  {
    city: 'Kinshasa',
    city_ascii: 'Kinshasa',
    country: 'Congo (Kinshasa)',
    iso2: 'CD',
    timezone: 'Africa/Kinshasa',
  },
  {
    city: 'Lahore',
    city_ascii: 'Lahore',
    country: 'Pakistan',
    iso2: 'PK',
    timezone: 'Asia/Karachi',
  },
  {
    city: 'Guangzhou',
    city_ascii: 'Guangzhou',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Bangalore',
    city_ascii: 'Bangalore',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Chicago',
    city_ascii: 'Chicago',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/Chicago',
  },
  {
    city: 'Bangkok',
    city_ascii: 'Bangkok',
    country: 'Thailand',
    iso2: 'TH',
    timezone: 'Asia/Bangkok',
  },
  {
    city: 'Hong Kong',
    city_ascii: 'Hong Kong',
    country: 'Hong Kong S.A.R.',
    iso2: 'HK',
    timezone: 'Asia/Hong_Kong',
  },
  {
    city: 'Chennai',
    city_ascii: 'Chennai',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Wuhan',
    city_ascii: 'Wuhan',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Tianjin',
    city_ascii: 'Tianjin',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Sydney',
    city_ascii: 'Sydney',
    country: 'Australia',
    iso2: 'AU',
    timezone: 'Australia/Sydney',
  },
  {
    city: 'Chongqing',
    city_ascii: 'Chongqing',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Chongqing',
  },
  {
    city: 'Baghdad',
    city_ascii: 'Baghdad',
    country: 'Iraq',
    iso2: 'IQ',
    timezone: 'Asia/Baghdad',
  },
  {
    city: 'Hyderabad',
    city_ascii: 'Hyderabad',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Paris',
    city_ascii: 'Paris',
    country: 'France',
    iso2: 'FR',
    timezone: 'Europe/Paris',
  },
  {
    city: 'Melbourne',
    city_ascii: 'Melbourne',
    country: 'Australia',
    iso2: 'AU',
    timezone: 'Australia/Melbourne',
  },
  {
    city: 'Taipei',
    city_ascii: 'Taipei',
    country: 'Taiwan',
    iso2: 'TW',
    timezone: 'Asia/Taipei',
  },
  {
    city: 'Lagos',
    city_ascii: 'Lagos',
    country: 'Nigeria',
    iso2: 'NG',
    timezone: 'Africa/Lagos',
  },
  {
    city: 'Toronto',
    city_ascii: 'Toronto',
    country: 'Canada',
    iso2: 'CA',
    timezone: 'America/Toronto',
  },
  {
    city: 'Ahmedabad',
    city_ascii: 'Ahmedabad',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Dongguan',
    city_ascii: 'Dongguan',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Ho Chi Minh City',
    city_ascii: 'Ho Chi Minh City',
    country: 'Vietnam',
    iso2: 'VN',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  {
    city: 'Riyadh',
    city_ascii: 'Riyadh',
    country: 'Saudi Arabia',
    iso2: 'SA',
    timezone: 'Asia/Riyadh',
  },
  {
    city: 'Shenzhen',
    city_ascii: 'Shenzhen',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Singapore',
    city_ascii: 'Singapore',
    country: 'Singapore',
    iso2: 'SG',
    timezone: 'Asia/Singapore',
  },
  {
    city: 'Chittagong',
    city_ascii: 'Chittagong',
    country: 'Bangladesh',
    iso2: 'BD',
    timezone: 'Asia/Dhaka',
  },
  {
    city: 'Shenyeng',
    city_ascii: 'Shenyeng',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Houston',
    city_ascii: 'Houston',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/Chicago',
  },
  {
    city: 'Chengdu',
    city_ascii: 'Chengdu',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Chongqing',
  },
  {
    city: 'St. Petersburg',
    city_ascii: 'St. Petersburg',
    country: 'Russia',
    iso2: 'RU',
    timezone: 'Europe/Moscow',
  },
  {
    city: 'Alexandria',
    city_ascii: 'Alexandria',
    country: 'Egypt',
    iso2: 'EG',
    timezone: 'Africa/Cairo',
  },
  {
    city: 'Belo Horizonte',
    city_ascii: 'Belo Horizonte',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Sao_Paulo',
  },
  {
    city: 'Pune',
    city_ascii: 'Pune',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Yokohama',
    city_ascii: 'Yokohama',
    country: 'Japan',
    iso2: 'JP',
    timezone: 'Asia/Tokyo',
  },
  {
    city: 'Rangoon',
    city_ascii: 'Rangoon',
    country: 'Myanmar',
    iso2: 'MM',
    timezone: 'Asia/Rangoon',
  },
  {
    city: 'Xian',
    city_ascii: 'Xian',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Chongqing',
  },
  {
    city: 'Luanda',
    city_ascii: 'Luanda',
    country: 'Angola',
    iso2: 'AO',
    timezone: 'Africa/Luanda',
  },
  {
    city: 'Ankara',
    city_ascii: 'Ankara',
    country: 'Turkey',
    iso2: 'TR',
    timezone: 'Europe/Istanbul',
  },
  {
    city: 'Philadelphia',
    city_ascii: 'Philadelphia',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/New_York',
  },
  {
    city: 'Abidjan',
    city_ascii: 'Abidjan',
    country: 'Ivory Coast',
    iso2: 'CI',
    timezone: 'Africa/Abidjan',
  },
  {
    city: 'Busan',
    city_ascii: 'Busan',
    country: 'South Korea',
    iso2: 'KR',
    timezone: 'Asia/Seoul',
  },
  {
    city: 'Harbin',
    city_ascii: 'Harbin',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Harbin',
  },
  {
    city: 'Nanjing',
    city_ascii: 'Nanjing',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Surat',
    city_ascii: 'Surat',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Khartoum',
    city_ascii: 'Khartoum',
    country: 'Sudan',
    iso2: 'SD',
    timezone: 'Africa/Khartoum',
  },
  {
    city: 'Hechi',
    city_ascii: 'Hechi',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Chongqing',
  },
  {
    city: 'Barcelona',
    city_ascii: 'Barcelona',
    country: 'Spain',
    iso2: 'ES',
    timezone: 'Europe/Madrid',
  },
  {
    city: 'Berlin',
    city_ascii: 'Berlin',
    country: 'Germany',
    iso2: 'DE',
    timezone: 'Europe/Berlin',
  },
  {
    city: 'Casablanca',
    city_ascii: 'Casablanca',
    country: 'Morocco',
    iso2: 'MA',
    timezone: 'Africa/Casablanca',
  },
  {
    city: 'Kabul',
    city_ascii: 'Kabul',
    country: 'Afghanistan',
    iso2: 'AF',
    timezone: 'Asia/Kabul',
  },
  {
    city: 'Kano',
    city_ascii: 'Kano',
    country: 'Nigeria',
    iso2: 'NG',
    timezone: 'Africa/Lagos',
  },
  {
    city: 'Brasilia',
    city_ascii: 'Brasilia',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Sao_Paulo',
  },
  {
    city: 'Salvador',
    city_ascii: 'Salvador',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Bahia',
  },
  {
    city: 'Montréal',
    city_ascii: 'Montréal',
    country: 'Canada',
    iso2: 'CA',
    timezone: 'America/Montreal',
  },
  {
    city: 'Dallas',
    city_ascii: 'Dallas',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/Chicago',
  },
  {
    city: 'Kanpur',
    city_ascii: 'Kanpur',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Miami',
    city_ascii: 'Miami',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/New_York',
  },
  {
    city: 'Fortaleza',
    city_ascii: 'Fortaleza',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Fortaleza',
  },
  {
    city: 'Jeddah',
    city_ascii: 'Jeddah',
    country: 'Saudi Arabia',
    iso2: 'SA',
    timezone: 'Asia/Riyadh',
  },
  {
    city: 'Haora',
    city_ascii: 'Haora',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Addis Ababa',
    city_ascii: 'Addis Ababa',
    country: 'Ethiopia',
    iso2: 'ET',
    timezone: 'Africa/Addis_Ababa',
  },
  {
    city: 'Guadalajara',
    city_ascii: 'Guadalajara',
    country: 'Mexico',
    iso2: 'MX',
    timezone: 'America/Mexico_City',
  },
  {
    city: 'Hanoi',
    city_ascii: 'Hanoi',
    country: 'Vietnam',
    iso2: 'VN',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  {
    city: 'Pyongyang',
    city_ascii: 'Pyongyang',
    country: 'North Korea',
    iso2: 'KP',
    timezone: 'Asia/Pyongyang',
  },
  {
    city: 'Santiago',
    city_ascii: 'Santiago',
    country: 'Chile',
    iso2: 'CL',
    timezone: 'America/Santiago',
  },
  {
    city: 'Nairobi',
    city_ascii: 'Nairobi',
    country: 'Kenya',
    iso2: 'KE',
    timezone: 'Africa/Nairobi',
  },
  {
    city: 'Changchun',
    city_ascii: 'Changchun',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Harbin',
  },
  {
    city: 'Cape Town',
    city_ascii: 'Cape Town',
    country: 'South Africa',
    iso2: 'ZA',
    timezone: 'Africa/Johannesburg',
  },
  {
    city: 'New Taipei',
    city_ascii: 'New Taipei',
    country: 'Taiwan',
    iso2: 'TW',
    timezone: 'Asia/Taipei',
  },
  {
    city: 'Taiyuan',
    city_ascii: 'Taiyuan',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Jaipur',
    city_ascii: 'Jaipur',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Dar es Salaam',
    city_ascii: 'Dar es Salaam',
    country: 'Tanzania',
    iso2: 'TZ',
    timezone: 'Africa/Dar_es_Salaam',
  },
  {
    city: 'Madrid',
    city_ascii: 'Madrid',
    country: 'Spain',
    iso2: 'ES',
    timezone: 'Europe/Madrid',
  },
  {
    city: 'Quezon City',
    city_ascii: 'Quezon City',
    country: 'Philippines',
    iso2: 'PH',
    timezone: 'Asia/Manila',
  },
  {
    city: 'Johannesburg',
    city_ascii: 'Johannesburg',
    country: 'South Africa',
    iso2: 'ZA',
    timezone: 'Africa/Johannesburg',
  },
  {
    city: 'Durban',
    city_ascii: 'Durban',
    country: 'South Africa',
    iso2: 'ZA',
    timezone: 'Africa/Johannesburg',
  },
  {
    city: 'Nagoya',
    city_ascii: 'Nagoya',
    country: 'Japan',
    iso2: 'JP',
    timezone: 'Asia/Tokyo',
  },
  {
    city: 'El Giza',
    city_ascii: 'El Giza',
    country: 'Egypt',
    iso2: 'EG',
    timezone: 'Africa/Cairo',
  },
  {
    city: 'Algiers',
    city_ascii: 'Algiers',
    country: 'Algeria',
    iso2: 'DZ',
    timezone: 'Africa/Algiers',
  },
  {
    city: 'Medellin',
    city_ascii: 'Medellin',
    country: 'Colombia',
    iso2: 'CO',
    timezone: 'America/Bogota',
  },
  {
    city: 'Porto Alegre',
    city_ascii: 'Porto Alegre',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Sao_Paulo',
  },
  {
    city: 'Surabaya',
    city_ascii: 'Surabaya',
    country: 'Indonesia',
    iso2: 'ID',
    timezone: 'Asia/Jakarta',
  },
  {
    city: 'Dalian',
    city_ascii: 'Dalian',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Lucknow',
    city_ascii: 'Lucknow',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    city: 'Recife',
    city_ascii: 'Recife',
    country: 'Brazil',
    iso2: 'BR',
    timezone: 'America/Recife',
  },
  {
    city: 'Faisalabad',
    city_ascii: 'Faisalabad',
    country: 'Pakistan',
    iso2: 'PK',
    timezone: 'Asia/Karachi',
  },
  {
    city: 'Incheon',
    city_ascii: 'Incheon',
    country: 'South Korea',
    iso2: 'KR',
    timezone: 'Asia/Seoul',
  },
  {
    city: 'Dakar',
    city_ascii: 'Dakar',
    country: 'Senegal',
    iso2: 'SM',
    timezone: 'Africa/Dakar',
  },
  {
    city: 'Boston',
    city_ascii: 'Boston',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/New_York',
  },
  {
    city: 'Detroit',
    city_ascii: 'Detroit',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/Detroit',
  },
  {
    city: 'Damascus',
    city_ascii: 'Damascus',
    country: 'Syria',
    iso2: 'SY',
    timezone: 'Asia/Damascus',
  },
  {
    city: 'Atlanta',
    city_ascii: 'Atlanta',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/New_York',
  },
  {
    city: 'Daegu',
    city_ascii: 'Daegu',
    country: 'South Korea',
    iso2: 'KR',
    timezone: 'Asia/Seoul',
  },
  {
    city: 'Izmir',
    city_ascii: 'Izmir',
    country: 'Turkey',
    iso2: 'TR',
    timezone: 'Europe/Istanbul',
  },
  {
    city: 'Washington, D.C.',
    city_ascii: 'Washington, D.C.',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/New_York',
  },
  {
    city: 'Hangzhou',
    city_ascii: 'Hangzhou',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Phoenix',
    city_ascii: 'Phoenix',
    country: 'United States of America',
    iso2: 'US',
    timezone: 'America/Phoenix',
  },
  {
    city: 'Zhangzhou',
    city_ascii: 'Zhangzhou',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Jinan',
    city_ascii: 'Jinan',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    city: 'Monterrey',
    city_ascii: 'Monterrey',
    country: 'Mexico',
    iso2: 'MX',
    timezone: 'America/Monterrey',
  },
  {
    city: 'Guiyang',
    city_ascii: 'Guiyang',
    country: 'China',
    iso2: 'CN',
    timezone: 'Asia/Chongqing',
  },
  {
    city: 'Caracas',
    city_ascii: 'Caracas',
    country: 'Venezuela',
    iso2: 'VE',
    timezone: 'America/Caracas',
  },
  {
    city: 'Nagpur',
    city_ascii: 'Nagpur',
    country: 'India',
    iso2: 'IN',
    timezone: 'Asia/Kolkata',
  },
];
