on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.js,*.mjs"
          token: ${{ secrets.GITHUB_TOKEN }}
